# C O D E B O O K 
## Human Activity Recognition Using Smarthphones (Version 1) Tidy Data Set of the University of Genoa, SmartLab

### 1. Study desing
This codebook describes the content of the **HAR_tidydata.txt** file. The file contains a database with 68 variables and 180 observations. This file was reformatted from the *[Version 1 of the Human Activity Recognition Using Smartphones Data Set](https://sites.google.com/view/smartlabunige/research)*, collected by the SmartLab of the University of Genoa in 2012. 

The **HAR_tidydata.txt** database was reformatted using the Tidy Data criteria recommended by Hadley Wickham (2014) in his *[Tidy Data](http://vita.had.co.nz/papers/tidy-data.pdf)* article.

The **HAR_tidydata.txt** database captures the normalized signals emitted by six different physical activities for 30 individuals between 19 and 48 years. The signals were recorded using the internal accelerometer and gyroscope of a Samsung Galaxy S II cellphone.

The **HAR_tidydata.txt** database was stored as a space-delimited text file. This means that it can be opened with any spreadsheet office software. However, for wider statistical purposes, the user may use the specialized statitistical software of her preference.

### 2. About the calculation of the variables
The identifiers of the **HAR_tidydata.txt** database are the subject and activity fields. The variables are the average per subject and activity of the movement signal features that were summarized for the original HAR data set. The measured movement features and their definitions are:

        BodyAcc: Body motion acceleration signal.
        Gyro: The angular body motion velocity signal.
        Gravity: The gravity body motion acceleration signal.
        Jerk: The acceleration-time derivative (dA/dt) signal.
        Frequency: Refers to the frequency domain used to calculate the signal.
        Time: Refers to the time domain used to calculate the signal.
        Mag: The magnitude of the three-dimensional signals calculated using the Euclidean norm.
        X, Y, Z: The three space dimensions along which the signals were taken.

Accordingly, each variable in  **HAR_tidydata.txt** database is the result of averaging the mean and standard deviation measures for each signal that results from the different combinaton of features by subject and activity. Other available summary statistics for the signals from the original data set (like maximum, minimum, and even the mean frequency) were not averaged for the calculation of variables of the **HAR_tidydata.txt** database.

To tidy and summarize the original dataset, these operations were executed using an R script:

        1. Two data sets, the training and the test data sets were merged identifying the subject and activity for each feature.
                1.1 Match the subject and activity id with measured features.
                1.2. Join the test and training data sets

        2. The mean and standard deviation measurements for each feature were extracted.
                2.1 Generate a record of the feature labels to be kept.
                2.2 Adjust features according to the position of the first two variables of the merged data set.
                2.3 Extract selected features indexing the record of features to be kept into the merged data set.

        3. The activity names was matched with their id.
                3.1 Match the activities id with the activity labels.
                3.2 Delete activity_id column and re-sort the column order.                                        
        4. Variable names were relabeled, special characters and typos were erased,  and single letters were defined.
                4.1 Clean special characters and typos
                4.1 Assign names according to the features keep data frame
                
        5. The merged data set was gathered by feature (key) and measure (value).
		
        6. This merged and gathered data set was grouped by subject, activity and feature. Then, a variable average was created for each feature.

        7.  The grouped data set was then spreaded by feature(key) and average(value).

### 3. Description of the variables
| ID | NAME                          | DESCRIPTION                                                                                                                                                                         | RANGE                                                                                   | UNITS       |
|----|-------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|-------------|
| 1  | subject                       | Number for one of the 30 volunteers within an age bracket of 19-48 years.                                                                                                           | [ 1, 30]                                                                                | A person    |
| 2  | activity                      | Activities performed by the each volunteer wearing a smartphone (Samsung Galaxy S II) on the waist.                                                                                 | [ "laying", "sitting", "standing", "walking", "walking_downstairs", "walking_upstairs"] | An activity |
| 3  | frequencyBodyAcc-mean-X       | Average measure per subject and activity of the mean frequency domain signals for the body motion acceleration along the X-axis                                                     | [-0.995,  0.537]                                                                        | Hz          |
| 4  | frequencyBodyAcc-mean-Y       | Average measure per subject and activity of the mean frequency domain signals for the body motion acceleration along the Y-axis                                                     | [-0.989,  0.524]                                                                        | Hz          |
| 5  | frequencyBodyAcc-mean-Z       | Average measure per subject and activity of the mean frequency domain signals for the body motion acceleration along the X-axis                                                     | [-0.989,  0.281]                                                                        | Hz          |
| 6  | frequencyBodyAcc-std-X        | Average measure per subject and activity of the standard deviation of the frequency domain signals for the body motion acceleration along the X-axis                                | [-0.997,  0.659]                                                                        | Hz          |
| 7  | frequencyBodyAcc-std-Y        | Average measure per subject and activity of thestandard deviation of the frequency domain signals for the body motion acceleration along the Y-axis                                 | [-0.991,  0.560]                                                                        | Hz          |
| 8  | frequencyBodyAcc-std-Z        | Average measure per subject and activity of thestandard deviation for the frequency domain signals for the body motion acceleration along the Z-axis                                | [-0.987,  0.687]                                                                        | Hz          |
| 9  | frequencyBodyAccJerk-mean-X   | Average measure per subject and activity of the mean of frequency domain signals for the body  motion acceletation time derivative (jerk) along the X-axis                          | [-0.995,  0.474]                                                                        | Hz          |
| 10 | frequencyBodyAccJerk-mean-Y   | Average measure per subject and activity of the mean of frequency domain signals for the body motion acceletation time derivative (jerk) along the Y-axis                           | [-0.989,  0.277]                                                                        | Hz          |
| 11 | frequencyBodyAccJerk-mean-Z   | Average measure per subject and activity of the mean of frequency domain signals for the body motion acceletation time derivative (jerk) along the Z-axis                           | [-0.992,  0.158]                                                                        | Hz          |
| 12 | frequencyBodyAccJerk-std-X    | Average measure per subject and activity of the standard deviation of the frequency domain signals for the body motion acceletation time derivative (jerk) along the X-axis         | [-0.995,  0.477]                                                                        | Hz          |
| 13 | frequencyBodyAccJerk-std-Y    | Average measure per subject and activity of the standard deviation of the frequency domain signals for the body motion acceletation time derivative (jerk) along the Y-axis         | [-0.990,  0.350]                                                                        | Hz          |
| 14 | frequencyBodyAccJerk-std-Z    | Average measure per subject and activity of the standard deviation of the frequency domain signals for the body motion acceletation time derivative (jerk) along the Z-axis         | [-0.993, -0.006]                                                                        | Hz          |
| 15 | frequencyBodyAccJerkMag-mean  | Average measure per subject and activity of the mean of the magnitude of the frequency domain signals for the body motion acceletation time derivative (jerk)                       | [-0.994,  0.538]                                                                        | Hz          |
| 16 | frequencyBodyAccJerkMag-std   | Average measure per subject and activity of the standard deviation of the magnitude of the frequency domain signals for the body motion acceletation time derivative (jerk)         | [-0.994,  0.316]                                                                        | Hz          |
| 17 | frequencyBodyAccMag-mean      | Average measure per subject and activity of the mean of the magnitude of the frequency domain signals for the body acceleration                                                     | [-0.987,  0.587]                                                                        | Hz          |
| 18 | frequencyBodyAccMag-std       | Average measure per subject and activity of the standard deviation of the magnitude of the frequency domain signals for the body acceleration                                       | [-0.988,  0.179]                                                                        | Hz          |
| 19 | frequencyBodyGyro-mean-X      | Average measure per subject and activity of the mean frequency domain signals for the body motion angular velocity along the X-axis                                                 | [-0.993,  0.475]                                                                        | Hz          |
| 20 | frequencyBodyGyro-mean-Y      | Average measure per subject and activity of the mean frequency domain signals for the body motion angular velocity along the Y-axis                                                 | [-0.994,  0.329]                                                                        | Hz          |
| 21 | frequencyBodyGyro-mean-Z      | Average measure per subject and activity of the mean frequency domain signals for the body motion angular velocity along the Z-axis                                                 | [-0.986,  0.492]                                                                        | Hz          |
| 22 | frequencyBodyGyro-std-X       | Average measure per subject and activity of the standard deviation frequency domain signals for the body motion angular velocity along the X-axis                                   | [-0.995,  0.197]                                                                        | Hz          |
| 23 | frequencyBodyGyro-std-Y       | Average measure per subject and activity of the standard deviation frequency domain signals for the body motion angular velocity along the Y-axis                                   | [-0.994,  0.646]                                                                        | Hz          |
| 24 | frequencyBodyGyro-std-Z       | Average measure per subject and activity of the mean standard deviation domain signals for the body motion angular velocity along the Z-axis                                        | [-0.987,  0.522]                                                                        | Hz          |
| 25 | frequencyBodyGyroJerkMag-mean | Average measure per subject and activity of the mean of the magnitude of the frequency domain signals for the body motion angular acceletation time derivative (jerk)               | [-0.998,  0.147]                                                                        | Hz          |
| 26 | frequencyBodyGyroJerkMag-std  | Average measure per subject and activity of the standard deviation of the magnitude of the frequency domain signals for the body motion angular acceletation time derivative (jerk) | [-0.998,  0.288]                                                                        | Hz          |
| 27 | frequencyBodyGyroMag-mean     | Average measure per subject and activity of the mean of the magnitude of the frequency domain signals for the body motion angular acceletation                                      | [-0.987,  0.204]                                                                        | Hz          |
| 28 | frequencyBodyGyroMag-std      | Average measure per subject and activity of the standard deviation of the magnitude of the frequency domain signals for the body motion angular acceletation                        | [-0.981,  0.237]                                                                        | Hz          |
| 29 | timeBodyAcc-mean-X            | Average measure per subject and activity of the mean time domain signals for the body motion acceleration along the X-axis                                                          | [ 0.222,  0.301]                                                                        | Hz          |
| 30 | timeBodyAcc-mean-Y            | Average measure per subject and activity of the mean time domain signals for the body motion acceleration along the Y-axis                                                          | [-0.041, -0.001]                                                                        | Hz          |
| 31 | timeBodyAcc-mean-Z            | Average measure per subject and activity of the mean time domain signals for the body motion acceleration along the Z-axis                                                          | [-0.153, -0.075]                                                                        | Hz          |
| 32 | timeBodyAcc-std-X             | Average measure per subject and activity of the standard deviation of the time domain signals for the body motion acceleration along the X-axis                                     | [-0.996,  0.627]                                                                        | Hz          |
| 33 | timeBodyAcc-std-Y             | Average measure per subject and activity of thestandard deviation of the time domain signals for the body motion acceleration along the Y-axis                                      | [-0.990,  0.617]                                                                        | Hz          |
| 34 | timeBodyAcc-std-Z             | Average measure per subject and activity of thestandard deviation for the time domain signals for the body motion acceleration along the Z-axis                                     | [-0.988,  0.609]                                                                        | Hz          |
| 35 | timeBodyAccJerk-mean-X        | Average measure per subject and activity of the mean of time domain signals for the body  motion acceletation time derivative (jerk) along the X-axis                               | [ 0.043,  0.130]                                                                        | Hz          |
| 36 | timeBodyAccJerk-mean-Y        | Average measure per subject and activity of the mean of time domain signals for the body motion acceletation time derivative (jerk) along the Y-axis                                | [-0.039,  0.057]                                                                        | Hz          |
| 37 | timeBodyAccJerk-mean-Z        | Average measure per subject and activity of the mean of time domain signals for the body motion acceletation time derivative (jerk) along the Z-axis                                | [-0.067,  0.038]                                                                        | Hz          |
| 38 | timeBodyAccJerk-std-X         | Average measure per subject and activity of the standard deviation of the time domain signals for the body motion acceletation time derivative (jerk) along the X-axis              | [-0.995,  0.544]                                                                        | Hz          |
| 39 | timeBodyAccJerk-std-Y         | Average measure per subject and activity of the standard deviation of the time domain signals for the body motion acceletation time derivative (jerk) along the Y-axis              | [-0.990,  0.355]                                                                        | Hz          |
| 40 | timeBodyAccJerk-std-Z         | Average measure per subject and activity of the standard deviation of the time domain signals for the body motion acceletation time derivative (jerk) along the Z-axis              | [-0.993,  0.031]                                                                        | Hz          |
| 41 | timeBodyAccJerkMag-mean       | Average measure per subject and activity of the mean of the magnitude of the time domain signals for the body motion acceletation time derivative (jerk)                            | [-0.993,  0.434]                                                                        | Hz          |
| 42 | timeBodyAccJerkMag-std        | Average measure per subject and activity of the standard deviation of the magnitude of the time domain signals for the body motion acceletation time derivative (jerk)              | [-0.995,  0.451]                                                                        | Hz          |
| 43 | timeBodyAccMag-mean           | Average measure per subject and activity of the mean of the magnitude of the time domain signals for the body acceleration                                                          | [-0.986,  0.645]                                                                        | Hz          |
| 44 | timeBodyAccMag-std            | Average measure per subject and activity of the standard deviation of the magnitude of the time domain signals for the body acceleration                                            | [-0.986,  0.428]                                                                        | Hz          |
| 45 | timeBodyGyro-mean-X           | Average measure per subject and activity of the mean time domain signals for the body motion angular velocity along the X-axis                                                      | [-0.206,  0.193]                                                                        | Hz          |
| 46 | timeBodyGyro-mean-Y           | Average measure per subject and activity of the mean time domain signals for the body motion angular velocity along the Y-axis                                                      | [-0.204,  0.027]                                                                        | Hz          |
| 47 | timeBodyGyro-mean-Z           | Average measure per subject and activity of the mean time domain signals for the body motion angular velocity along the Z-axis                                                      | [-0.072,  0.179]                                                                        | Hz          |
| 48 | timeBodyGyro-std-X            | Average measure per subject and activity of the standard deviation time domain signals for the body motion angular velocity along the X-axis                                        | [-0.994,  0.268]                                                                        | Hz          |
| 49 | timeBodyGyro-std-Y            | Average measure per subject and activity of the standard deviation time domain signals for the body motion angular velocity along the Y-axis                                        | [-0.994,  0.477]                                                                        | Hz          |
| 50 | timeBodyGyro-std-Z            | Average measure per subject and activity of the mean standard deviation domain signals for the body motion angular velocity along the Z-axis                                        | [-0.986,  0.565]                                                                        | Hz          |
| 51 | timeBodyGyroJerk-mean-X       | Average measure per subject and activity of the mean of time domain signals for the body  motion angular acceletation time derivative (jerk) along the X-axis                       | [-0.157, -0.022]                                                                        | Hz          |
| 52 | timeBodyGyroJerk-mean-Y       | Average measure per subject and activity of the mean of time domain signals for the body motion angular acceletation time derivative (jerk) along the Y-axis                        | [-0.077, -0.013]                                                                        | Hz          |
| 53 | timeBodyGyroJerk-mean-Z       | Average measure per subject and activity of the mean of time domain signals for the body motion angular acceletation time derivative (jerk) along the Z-axis                        | [-0.092, -0.007]                                                                        | Hz          |
| 54 | timeBodyGyroJerk-std-X        | Average measure per subject and activity of the standard deviation of time domain signals for the body  motion angular acceletation time derivative (jerk) along the X-axis         | [-0.997,  0.179]                                                                        | Hz          |
| 55 | timeBodyGyroJerk-std-Y        | Average measure per subject and activity of the standard deviation of time domain signals for the body motion angular acceletation time derivative (jerk) along the Y-axis          | [-0.997,  0.296]                                                                        | Hz          |
| 56 | timeBodyGyroJerk-std-Z        | Average measure per subject and activity of the standard deviation of time domain signals for the body motion angular acceletation time derivative (jerk) along the Z-axis          | [-0.995,  0.193]                                                                        | Hz          |
| 57 | timeBodyGyroJerkMag-mean      | Average measure per subject and activity of the mean of the magnitude of the time domain signals for the body motion angular acceletation time derivative (jerk)                    | [-0.997,  0.088]                                                                        | Hz          |
| 58 | timeBodyGyroJerkMag-std       | Average measure per subject and activity of the standard deviation of the magnitude of the time domain signals for the body motion angular acceletation time derivative (jerk)      | [-0.998,  0.250]                                                                        | Hz          |
| 59 | timeBodyGyroMag-mean          | Average measure per subject and activity of the mean of the magnitude of the time domain signals for the body motion angular acceletation                                           | [-0.981,  0.418]                                                                        | Hz          |
| 60 | timeBodyGyroMag-std           | Average measure per subject and activity of the standard deviation of the magnitude of the time domain signals for the body motion angular acceletation                             | [-0.981,  0.300]                                                                        | Hz          |
| 61 | timeGravityAcc-mean-X         | Average measure per subject and activity of the mean time domain signals for the body motion gravity acceleration along the X-axis                                                  | [-0.680,  0.975]                                                                        | Hz          |
| 62 | timeGravityAcc-mean-Y         | Average measure per subject and activity of the mean time domain signals for the body motion gravity acceleration along the Y-axis                                                  | [-0.480,  0.957]                                                                        | Hz          |
| 63 | timeGravityAcc-mean-Z         | Average measure per subject and activity of the mean time domain signals for the body motion gravity acceleration along the Z-axis                                                  | [-0.495,  0.958]                                                                        | Hz          |
| 64 | timeGravityAcc-std-X          | Average measure per subject and activity of the standard deviation time domain signals for the body motion gravity acceleration along the X-axis                                    | [-0.997, -0.830]                                                                        | Hz          |
| 65 | timeGravityAcc-std-Y          | Average measure per subject and activity of the standard deviation time domain signals for the body motion gravity acceleration along the Y-axis                                    | [-0.994, -0.644]                                                                        | Hz          |
| 66 | timeGravityAcc-std-Z          | Average measure per subject and activity of the standard deviation time domain signals for the body motion gravity acceleration along the Z-axis                                    | [-0.991, -0.610]                                                                        | Hz          |
| 67 | timeGravityAccMag-mean        | Average measure per subject and activity of the mean of the magnitude of the time domain signals for the body motion gravity acceleration                                           | [-0.986,  0.645]                                                                        | Hz          |
| 68 | timeGravityAccMag-std         | Average measure per subject and activity of the standard deviation of the magnitude of the time domain signals for the body motion gravity acceleration                             | [-0.986,  0.428]                                                                        | Hz          |